---
resources:
  - name: filelist-ng-git
    type: git
    icon: gitty
    source:
      uri: https://code.dfau.de/dfau/filelist-ng.git

jobs:
  - name: test
    public: true
    plan:
      - get: filelist-ng-git
        trigger: true
      - task: run-tests
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: { repository: php, tag: 7.3-cli }
          inputs:
            - name: filelist-ng-git
          run:
            path: /bin/sh
            args:
              - -c
              - |
                apt-get update
                apt-get install -y git unzip

                php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
                php -r "if (hash_file('sha384', 'composer-setup.php') === 'e0012edf3e80b6978849f5eff0d4b4e4c79ff1609dd1e613307e16318854d24ae64f26d17af3ef0bf7cfb710ca74755a') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
                php composer-setup.php --install-dir=/usr/local/bin --filename=composer
                php -r "unlink('composer-setup.php');"

                cd laravel-websockets-git

                composer install
                vendor/bin/phpunit Tests/Unit
