services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  TYPO3\CMS\Mediamanager\:
    resource: '../Classes/*'

  TYPO3\CMS\Mediamanager\Backend\Browser\:
    resource: '../Classes/Backend/Browser/*'
    public: true
    autoconfigure: false

  TYPO3\CMS\Mediamanager\Backend\Browser\FileBrowser:
    decorates: TYPO3\CMS\Recordlist\Browser\FileBrowser

  TYPO3\CMS\Mediamanager\Backend\Browser\FolderBrowser:
    decorates: TYPO3\CMS\Recordlist\Browser\FolderBrowser

  TYPO3\CMS\Mediamanager\Backend\Clipboard\MediamanagerAwareClipboard:
    decorates: TYPO3\CMS\Backend\Clipboard\Clipboard

  TYPO3\CMS\Mediamanager\Backend\ContextMenu\FileProvider:
    decorates: TYPO3\CMS\Filelist\ContextMenu\ItemProviders\FileProvider

  TYPO3\CMS\Mediamanager\Backend\Controller\:
    resource: '../Classes/Backend/Controller/*'
    public: true

  TYPO3\CMS\Mediamanager\Backend\Controller\MediamanagerController:
    tags: ['backend.controller']

  TYPO3\CMS\Mediamanager\Backend\EventListener\ModifyFolderIconListener:
    tags:
      - name: event.listener
        identifier: 'mediamanager-modify-folder-icon'
        event: TYPO3\CMS\Core\Imaging\Event\ModifyIconForResourcePropertiesEvent
