services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  TYPO3\CMS\FilelistNg\:
    resource: '../Classes/*'

  TYPO3\CMS\FilelistNg\Backend\Controller\:
    resource: '../Classes/Backend/Controller'
    public: true

  TYPO3\CMS\FilelistNg\Backend\Controller\FilelistController:
    tags: ['backend.controller']
