services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  TYPO3\CMS\Mediamanager\:
    resource: '../Classes/*'

  TYPO3\CMS\Mediamanager\Backend\Browser\:
    resource: '../Classes/Backend/Browser/*'
    public: true

  TYPO3\CMS\Mediamanager\Backend\Controller\:
    resource: '../Classes/Backend/Controller/*'
    public: true

  TYPO3\CMS\Mediamanager\Backend\Controller\MediamanagerController:
    tags: ['backend.controller']
