name: Backend-CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ '8.1' ]
        include:
          - php: '8.1'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up PHP version ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2, php-cs-fixer

      - name: Environment Check
        run: |
          php --version
          composer --version

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: |
          composer install
      - name: Info
        run: composer info

      - name: CGL
        run: php-cs-fixer fix --verbose --config ./Build/.php-cs-fixer.php --dry-run

      - name: Unit Tests
        run: ./etc/scripts/runTests.sh -s unit

      - name: Functional Tests
        run: ./etc/scripts/runTests.sh -s function
