name: Frontend-CI

on: [ push, pull_request ]

defaults:
  run:
    working-directory: ./Build
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.x ]
      fail-fast: false

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Build dev
        run: npm run build:dev

      - name: CGL
        run: npm run lint

      - name: Run tests
        run: npm run test:ci
